# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_homepage_feed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(default='', max_length=255, verbose_name='Document Object Identifier'),
            preserve_default=False,
        ),
    ]
