# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_publication_doi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(blank=True, max_length=255)),
                ('abstract', wagtail.wagtailcore.fields.RichTextField()),
                ('identifier', models.CharField(max_length=6, verbose_name='Research Application Identifier')),
            ],
        ),
    ]
