# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='identifier',
            field=models.CharField(help_text='Not for public display', max_length=6, verbose_name='Research Application Identifier'),
        ),
    ]
