# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170810_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.CharField(max_length=255),
        ),
    ]
