# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20171020_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='repeated_item_text',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='repeated_item_text',
        ),
    ]
