# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20171020_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
