# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_multipage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
