# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 17:23
from __future__ import unicode_literals

from django.db import migrations
import quodsite.website.models
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20180227_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='website/blocks/table.html')), ('publications_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailsnippets.blocks.SnippetChooserBlock(quodsite.website.models.Publication, label='publication'), template='website/blocks/publications_list.html')), ('projects_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailsnippets.blocks.SnippetChooserBlock(quodsite.website.models.Project, label='project'))), ('qa_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('question', wagtail.wagtailcore.blocks.RichTextBlock()), ('answer', wagtail.wagtailcore.blocks.RichTextBlock())), label='entry'), template='website/blocks/qa_list.html')))),
        ),
    ]
