# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_variables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='SessionVariablesNumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
