# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_variables', '0002_session_sessionvariablesnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=45)),
                ('session', models.PositiveIntegerField()),
                ('version', models.CharField(max_length=45)),
                ('timestamp', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('saves', models.PositiveIntegerField()),
                ('archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NewVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('section', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='newsession',
            name='variables',
            field=models.ManyToManyField(to='research_variables.NewVariable'),
        ),
    ]
