# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_variables', '0004_auto_20180315_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcategory',
            name='category_id',
        ),
        migrations.AddField(
            model_name='newsection',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='research_variables.NewCategory'),
            preserve_default=False,
        ),
    ]
