# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_variables', '0005_auto_20180316_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsection',
            name='level',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsection',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
