# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_variables', '0007_auto_20180316_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
