# Generated by Django 2.0.4 on 2018-04-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_variables', '0008_auto_20180326_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='NewSection',
            new_name='Section',
        ),
        migrations.RenameModel(
            old_name='NewSession',
            new_name='Session',
        ),
        migrations.RenameModel(
            old_name='NewVariable',
            new_name='Variable',
        ),
    ]

    atomic = False
