# Generated by Django 2.0.4 on 2018-05-03 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_variables', '0009_auto_20180413_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='level',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='category',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='version',
        ),
        migrations.AlterField(
            model_name='variable',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_variables.Section'),
        ),
    ]
